# Matlab

* język wysokiego poziomu do obliczeń numerycznych, wizualizacji i tworzenia aplikacji
* interaktywne środowisko do iteracyjnej eksploracji, projektowania i rozwiązywania problemów
* obszerna bibliotekę funkcji matematycznych dla algebry liniowej, statystyki, analizy Fouriera, filtrowania, optymalizacji, całkowania numerycznego i rozwiązywania zwykłych równań różniczkowych
*  wizualizacja danych
*  narzędzia programistyczne: edutor, debbuger, profiler, ... 
*  narzędzia do tworzenia aplikacji z interfejsami graficznymi
*  integracja algorytmów z zewnętrznymi aplikacjami (np. MS Excel) i językami (C, Java, .NET, ...)


## Srodowisko graficzne

<img src="https://ch.mathworks.com/help/matlab/learn_matlab/desktop.png" />

* **Current Folder**  katalog bierzący
* **Command Window** linia komend 
* **Workspace** podgląd zmiennych i danych w projekcie 
* **Command History** historia komend



## Operacje arytmetyczne - Matlab jako kalkulator

`+` dodawnie, `-` odejmowanie, `*` mnożenie, `/` dzielenie, `^` potęgowanie



In [22]:
5 + 5

ans =  10


In [23]:
2 ^ 10

ans =  1024


In [24]:
3 / 5

ans =  0.60000


In [25]:
3 / 0 

ans =  Inf


## Funkcje i stałe matematyczne

`sin()`, `cos()`, `sqrt()`, `exp()`
`pi` $\pi$, 

In [26]:
sin( pi / 4 )

ans =  0.70711


In [27]:
sqrt(16)

ans =  4


In [31]:
sqrt(-1)

ans =  0 + 1i


## Wyjście poleceń

* średnik na końcu instrukcji (;) wyłacza wyjście
* `disp()` wypisywanie zmiennych 
* `fprintf()` wypisywanie formatowanych komunikatów zgodnie z funkcją `printf` z C

In [16]:
sin(5) + 3;

In [1]:
disp(sin(5) + 3);
disp('Witaj świecie')

 2.0411
Witaj świecie


In [5]:
fprintf('Witaj ściecie!\n')
fprintf('sin(2)=%f\n', sin(2))

Witaj ściecie!
sin(2)=0.909297


## Zmienne
    
* definicja i inicjalizacja zmiennych 

In [14]:
x = 16 
y = sqrt(x)
z = x + y + sin(x) 
napis = 'Witaj Świecie'

x =  16
y =  4
z =  19.712
napis = Witaj Świecie


* `who` - lista zmiennych 
* `whos` - lista zmiennych wraz informacją o typie 

In [12]:

who

Variables in the current scope:

ans    napis  x      y      z



In [15]:
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        ans         1x5                          5  char
        napis       1x14                        14  char
        x           1x1                          8  double
        y           1x1                          8  double
        z           1x1                          8  double

Total is 22 elements using 43 bytes



* zmienne liczbowe są macierzami 1x1
* napisy są wektorem znaków (`char`) 1xN

## Zmienna `ans`

* zmienna `ans` przechowuje ostatni wynik (answer)

In [18]:
sqrt(2)

ans =  1.4142


In [19]:
x = ans + 5

x =  6.4142


## Typy danych

* typy: całkowity `int32`, liczby rzeczywiste `double`, typ logiczny `logical`, typ znakowy `char`


In [50]:
i = 1
x = 1
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        ans         1x1                          1  char
        i           1x1                          8  double
        napis       1x14                        14  char
        x           1x1                          8  double
   c    y           1x1                         16  double
        z           1x1                          8  double

Total is 19 elements using 55 bytes

i =  1


## Wektory

In [63]:
x = [ 1  2  3]

   1   2   3


In [68]:
x = [ 1,  2,  3]

x =

   1   2   3



In [69]:
x = 1:10

x =

   1   2   3



In [71]:
x = [ 1 ; 2 ; 3 ; 4]

x =

   1
   2
   3
   4



## Operacje na wektorach

In [91]:
x = [1 2 3 4 5]
x + 2

ans =

   3   4   5   6   7



In [97]:
sqrt(x)

ans =

   1.0000   1.4142   1.7321   2.0000   2.2361



In [100]:
y = [6 7 8 9 10]
z = x + y
sqrt(x)

ans =

   1.0000   1.4142   1.7321   2.0000   2.2361

y =

    6    7    8    9   10



## Wykresy

In [105]:
x = 1:10
plot(sin(x))

error: print: directory /tmp/tmp0qhbdct9 does not exist
error: called from
    _make_figures>safe_print at line 125 column 7
    _make_figures at line 49 column 13


## Komendy wbudowane

* `cls` 
* `clear x` usuwa zmienną `x`
* `clear` usuwa wszystkie zmienne
* `help polecenie` pomoc 
* `quit` wyjście z Matlab
* `who` `whos` 

In [107]:
help  help

'help' is a function from the file /usr/share/octave/5.2.0/m/help/help.m

 -- help NAME
 -- help --list
 -- help .
 -- help
     Display the help text for NAME.

     For example, the command 'help help' prints a short message
     describing the 'help' command.

     Given the single argument '--list', list all operators, keywords,
     built-in functions, and loadable functions available in the current
     session of Octave.

     Given the single argument '.', list all operators available in the
     current session of Octave.

     If invoked without any arguments, 'help' displays instructions on
     how to access help from the command line.

     The help command can provide information about most operators, but
     NAME must be enclosed by single or double quotes to prevent the
     Octave interpreter from acting on NAME.  For example, 'help "+"'
     displays help on the addition operator.

     See also: doc, lookfor, which, info.

Additional help for built-in functions and 

## Skrypty

tryby pracy:
* interaktywny - w wierszu poleceń
* wsadowy - plik `*.m` zawierający ciąg instrukcji staje się poleceniem Matlab 

In [114]:
hello

tekst = Witaj Świecie
Witaj Świecie


* `type nazwa` wyświetla zawartość pliku
* `edit nazwa` otwiera edycję pliku 

In [119]:
type hello

hello is the user-defined function defined from: /home/marek/work/zajecia/2020.zimowy/pp2/github/hello.m

tekst = 'Witaj Świecie'

disp(tekst)



## Komendy systemowe

* `cd` zmiana katalogu
* `date` data
* `dir` zawartość katalogu
* `pwd` bieżący katalog
* `save` zapis zmiennych, `load` odczytanie zmiennych


In [123]:
help type

'type' is a function from the file /usr/share/octave/5.2.0/m/help/type.m

 -- type NAME ...
 -- type -q NAME ...
 -- text = type ("NAME", ...)
     Display the contents of NAME which may be a file, function
     (m-file), variable, operator, or keyword.

     'type' normally prepends a header line describing the category of
     NAME such as function or variable; The '-q' option suppresses this
     behavior.

     If no output variable is used the contents are displayed on screen.
     Otherwise, a cell array of strings is returned, where each element
     corresponds to the contents of each requested function.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at https://www.octave.org and via the help@octave.org
mailing list.


In [125]:
type x

x is a variable
    1    2    3    4    5    6    7    8    9   10



In [127]:
bar([1,2,3])

Inline plot failed, consider trying another graphics toolkit
error: print: directory /tmp/tmpa0kl1wno does not exist
error: called from
    _make_figures>safe_print at line 125 column 7
    _make_figures at line 49 column 13



## Zadanie

Napisz skrypt o nazwie `zad1.m`, który wykona nastepujące instrukcje:
* wypisze Twoje imię i numer indeksu
* wypisze wartość $f(x)$ w punkcie $x=3$
$$ f(x) = \frac{1}{\sqrt{2\pi}}cos(x) \cdot e^{-2 x}$$
* wyrysuje wykres $f(x)$  