# Macierze - uzupełnienie

* tworzenie macierzy i indeksowanie elementów macierzy
* operacje macierzowe i funkcje działające na macierzach
* macierze logiczne i operacje na macierzach logicznych
* optymalizacja kodu
 * wektoryzacja - zamiana pętli po elementach na mechanizmy indeksowania
 * prealokacja - dynamiczne modyfikowanie rozmiarów macierzy jest kosztowne



## Operacje na macierzach

TODO zebrac operatory

* operacje skalarne na elementach macierzy:  `+`, `-`, `*`, `/`, `.^`, `.\`

In [45]:
A = [1 2 3; 4 5 6]

A =

   1   2   3
   4   5   6



In [55]:
a = A + 3     # to samo co A .+ 3
b = A * 5     # to samo co A .* 5
c = A / 5     # to samo co A ./ 5

a =

   4   5   6
   7   8   9

b =

    5   10   15
   20   25   30

c =

   0.20000   0.40000   0.60000
   0.80000   1.00000   1.20000



In [57]:
d = A .^ 2     
e = A .\ 5    # to samo co 5 ./ A

d =

    1    4    9
   16   25   36

e =

   5.00000   2.50000   1.66667
   1.25000   1.00000   0.83333



* operacje macierzowe: `*`, `/`, `\`
 * `A * B` iloczyn macierzy (iloczyn skalarny dla wektorów) 
 * `A / B` dzielenie macierzy, wynikiem jest `X` takie, że `X * B = A`
 * `A \ B`  dzielenie macierzy, wynikiem jest `X` takie, że `A * X = B`
 * potęgowanie `A^n` tylko dla macierzy `A` kwadratowych

In [67]:
A = [1 2 3; 4 5 6]
B = [1 2 3; 4 5 6]
a = A * B';  # ilość wierszy A == ilość kolumn B
b = A / B ;  # wymiary A i B takie same
c = A \ B   # wymiary A i B takie same

A =

   1   2   3
   4   5   6

B =

   1   2   3
   4   5   6

c =

   0.83333   0.33333  -0.16667
   0.33333   0.33333   0.33333
  -0.16667   0.33333   0.83333

ans =

   1.0000   2.0000   3.0000
   4.0000   5.0000   6.0000



In [74]:
d = A(1:2,1:2)^2

d =

    9   12
   24   33



* opearcje macierzowe element po elemencie: `+`, `-`, `.*`, `./`, `.^`, `.\`
* wymiary macierzy muszą się zgadzać

In [81]:
A = [ 1 2 3; 4 5 6 ]
B = [ 3 4 6; 3 4 3 ]

a = A + B ;   # to samo co A .+ B
b = A .* B
c = A ./ B

A =

   1   2   3
   4   5   6

B =

   3   4   6
   3   4   3

b =

    3    8   18
   12   20   18

c =

   0.33333   0.50000   0.50000
   1.33333   1.25000   2.00000



In [80]:
d = A .^ B
e = A .\ B  # to samo co B ./ A

d =

     1    16   729
    64   625   216

e =

   3.00000   2.00000   2.00000
   0.75000   0.80000   0.50000



* operacje macierzy i wektora element po elemencie powielane wzdłuż pasującego wymiaru

In [ ]:
A = ones(2, 3) + 1
w1 = [1 2 3]
w2 = [1; 2]

In [ ]:
a = A + w1    # sumowanie elementów w wierszach macierzy
b = A + w2    # sumowanie elementów w kolumnach macierzy 

In [ ]:
a = A .* w1    
b = A .* w2

## Macierze i funkcje

Wiele funkcji Matlaba jest przystosowana do działania na macierzach o dowolnych kształtach


In [ ]:
w = 1:6
X = reshape(w, 2, 3)

a = sin(w)
b = cos(X)

**Ćwiczenie** popraw program `pole_kola.m` tak aby funkcja zwracała poprawny wynik dla argumentu macierzowego. Wynikiem funkcji będzie macierz zawierająca w każdym z elementów  $P_{ij}$ wartość pola dla promienia $R_{ij}$.
Postaraj się nie korzystać z instrukcji pętli. 

**Ćwiczenie** zmierz czas wykonywania poniższych instrukcji.
* porównaj szybkość działania przy zastosowaniu prealokowanego wektora `x`
* przyśpiesz działanie stosując wektoryzację (pozbądź się instrukcji pętli)

In [ ]:
n=100000
tic
for i=1:n
    x(i) = sqrt(i);
end
toc
sum(x)

## Wektory i macierze logiczne

* macierze zawierające wartości logiczne (typ `logical`), wartość `0` to fałsz, wartość `1` (lub niezerowa) to prawda
* indeksowanie macierzy za pomocą macierzy logicznych
* funkcje `false()` i `true()` pozwalają tworzyć macierze logiczne
* funkcja `logical()` zamienia macierz liczbową na logiczną

In [85]:
X = [1 , -5, 7 ; -1, 42, -12]
ind = X < 0
whos ind

X =

    1   -5    7
   -1   42  -12

ind =

  0  1  0
  1  0  1

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        ind         2x3                          6  logical

Total is 6 elements using 6 bytes



In [84]:
# indeksowanie macierzą logiczną
a = X(ind)    
b = X( X > 0 )
X( X > 0) = 111

a =

   -1
   -5
  -12

b =

    1
   42
    7

X =

   111    -5   111
    -1   111   -12



In [ ]:
A = true(2)
B = false(2, 3)
whos A B

In [ ]:
# wartości logiczne mogą być traktowane jak liczby całkowite
C = A + 1
whos A C

**Ćwiczenie** dlaczego poniższe wyrażenie nie działa? Spróbuj to naprawić.

In [ ]:
w = 1:5;
w([1 0 1 0 1]) = -1

## Przydatne funkcje operujące na wartościach logicznych

* `any()` zwraca 1 gdy wektor posiada niezerowy element,  
dla macierzy zwraca wektor z wartością 1 gdy w kolumnie jest niezerowa wartość   
* `all()` zwraca 1 dla każdej kolumny której wszystkie elementy są niezerowe
* `find()` zwraca indeksy (indeksowanie liniowe) niezerowych elementów
* `isequal()` sprawdza czy macierze mają jednakowe elementy


In [ ]:
w1 = [ 0 0 1 2 ];
w2 = zeros(1,10);

a = all(w1)
b = any(w1)

c = all(w2)
d = any(w2)

In [ ]:
E = [ 1 2 ; 0 0 ; 3 * eye(2)]'
all(E)
any(E)

In [ ]:
# indeksy liniowe
k = find(E)
a = E(k)

In [ ]:
# indeksy wierszy i kolumn
[w k] = find(E)

In [ ]:
# szukanie zerowych elementów
k2 = find(~E)

In [ ]:
# szukanie elementów spełniających warunki
k3 = find(E > 2)

In [ ]:
X = E
isequal(E, X)

% to samo za pomocą funkcji all()
all(all(X == E))   

X(1,1) = -X(1,1)
isequal(E, X)
all(all(X == E))   


## Operatory logiczne

* operatory logiczne działające element po elemencie: `&` and, `|` or, `~` not

In [ ]:
X = magic(5)
X(X > 5 & X < 10)


**Ćwiczenie** utwórz macierz `X` o wymiarach 10x10 posiadającą losowe wartości z zakresu od -1 do 1. 
Następnie zastąp wszystkie elementy o wartości ujemnej w macierzy `X` liczbą `0`.

## Zadanie 6 ???

Napisz funkcję o nazwie 