# Struktury i  cell array 

* elementami macierzy są wartości tego samego typu (bool, int, double, char)
* **struktura** (/struct/) typ danych pozwalający przechowywac wiele wartości różego typu. Poszczególne wartości dostępne są w nazwanych **polach**

* **macierz komurkowa** (/cell array/) pozwala w sposób macierzy przechowywać dane różnego typu. Poszczególne wartości dostępne są za pomocą indeksów liczbowych


## Obiekt typu cell

In [19]:
# komórka (cell)
a = { 42 }
b = { 'A' }
c = { 'Siała baba mak' }
whos a b c

a =
{
  [1,1] =  42
}

b =
{
  [1,1] = A
}

c =
{
  [1,1] = Siała baba mak
}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x1                          8  cell
        b           1x1                          1  cell
        c           1x1                         15  cell

Total is 3 elements using 24 bytes



## Wektory i macierze typu cell

In [23]:
# wektor wierszowy
c = { 42, 'A', 1:3:10, 'Witaj'} 
whos c

c =
{
  [1,1] =  42
  [1,2] = A
  [1,3] =

      1    4    7   10

  [1,4] = Witaj
}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        c           1x4                         38  cell

Total is 4 elements using 38 bytes



In [42]:
# wektor kolumnowy
c = { 42; 'A'; 1:3:10; 'Witaj'} 
size(c)

c =
{
  [1,1] =  42
  [2,1] = A
  [3,1] =

      1    4    7   10

  [4,1] = Witaj
}

ans =

   4   1



In [44]:
# macierz 2x2
c = { 42, 'A'; 1:3:10, 'Witaj'} 
size(c)

c =
{
  [1,1] =  42
  [2,1] =

      1    4    7   10

  [1,2] = A
  [2,2] = Witaj
}

ans =

   2   2



In [43]:
## pusta macierz - prealikacja macierzy komórkowej
x = cell(2, 3)

x =
{
  [1,1] = [](0x0)
  [2,1] = [](0x0)
  [1,2] = [](0x0)
  [2,2] = [](0x0)
  [1,3] = [](0x0)
  [2,3] = [](0x0)
}

ans =

   2   3



## Indeksowanie elementów obiektu typu cell

* nawiasy klamrowe `{i, j}` dają dostęp do wartości w komórkach
* nawiasy okrągłe `(i, j)` dają dostęp komórek (wynik jest opiektem typu cell)

In [48]:
x = { 42, 'A'; 1:3:10, 'Witaj'};

% indeksowanie wartości (1,1)
a = x{1,1}

# indeksowanie komórek
b = x(1, 1)
whos a b

a =  42
b =
{
  [1,1] =  42
}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x1                          8  double
        b           1x1                          8  cell

Total is 2 elements using 16 bytes



In [53]:
% indeksowanie wartości (1,1)
a = x{2,1}

# indeksowanie komórek
b = x(2, 1)
whos a b

c = x{2, 1}(1)   
d = x(2, 1){1}(1)
whos c d

a =

    1    4    7   10

b =
{
  [1,1] =

      1    4    7   10

}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x4                         24  double
        b           1x1                         24  cell

Total is 5 elements using 48 bytes

c =  1
d =  1
Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        c           1x1                          8  double
        d           1x1                          8  double

Total is 2 elements using 16 bytes



## Ineksowanie za pomoca dwukropka :

In [ ]:
x = { 42, 'A', 1:3:10, 'Matlab'};

# pierwsze 3 elementy - 3 różne zmienne
x{1:3}

In [58]:
[a b c] = x{1:3}

whos a b c

a =  42
b = A
c =

    1    4    7   10

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x1                          8  double
        b           1x1                          1  char
        c           1x4                         24  double

Total is 6 elements using 33 bytes



In [66]:
x{:}

ans =  42
ans = A
ans =

    1    4    7   10

ans = Matlab


In [67]:
% wynikiem x(1:3) nowa macierz komórkowa
a = x(1:3)
whos a x

a =
{
  [1,1] =  42
  [1,2] = A
  [1,3] =

      1    4    7   10

}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x3                         33  cell
        x           1x4                         39  cell

Total is 7 elements using 72 bytes



## Wyświetlanie zawartości komórek

* `celldisp()` wypisuje zawartość kolejnych komórek
* `cellplot()` wypisanie wartości w trybie graficznym (w oknie)

In [ ]:
x = { 42, 'A', 1:3:10, 'Matlab'};

disp(x)
celldisp(x)

In [ ]:
% wyświetlanie rekurencyjne
celldisp({1, 2, x})

In [84]:
% celplot() nie jest dostępne w Octave
cellplot(x)

{1} = 

 1

{2} = 

 2

{3}{1} = 

 42

{3}{2} = 

A

{3}{3} = 

    1    4    7   10

{3}{4} = 

Matlab


Please read <https://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
error: 'cellplot' undefined near line 2 column 1


## Funkcje macierzowe

* wiele funkcji i operacji macierzowych działa również na komórkach
* `iscell()` spradza, cze zmienna jest typu cell

In [82]:
x = { 42, 'A'; 1:3:10, 'Matlab'};

% rozmiar
[w k] = size(x)

% transpozycja
y = x'
celldisp(x)

% zmiana kształtu
reshape(x, [1, 4])

% usuwanie elementów
x(1, :) = []
celldisp(x)

help celldisp

w =  2
k =  2
y =
{
  [1,1] =  42
  [2,1] = A
  [1,2] =

      1    4    7   10

  [2,2] = Matlab
}

x{1,1} = 

 42

x{2,1} = 

    1    4    7   10

x{1,2} = 

A

x{2,2} = 

Matlab

ans =
{
  [1,1] =  42
  [1,2] =

      1    4    7   10

  [1,3] = A
  [1,4] = Matlab
}

x =
{
  [1,1] =

      1    4    7   10

  [1,2] = Matlab
}

x{1} = 

    1    4    7   10

x{2} = 

Matlab

'celldisp' is a function from the file /usr/share/octave/5.2.0/m/general/celldisp.m

 -- celldisp (C)
 -- celldisp (C, NAME)
     Recursively display the contents of a cell array.

     By default the values are displayed with the name of the variable
     C.  However, this name can be replaced with the variable NAME.  For
     example:

          c = {1, 2, {31, 32}};
          celldisp (c, "b")
             =>
                b{1} =
                 1
                b{2} =
                 2
                b{3}{1} =
                 31
                b{3}{2} =
                 32

     See also: disp.

Addi

## Macierz komórkowa z napisami

* w obiekcie typu cell mozna przechowywać napisy o różnej długości

In [86]:
tekst = {'Ala ma kota', 'Siała baba mak', 'Matlab'} 

tekst =
{
  [1,1] = Ala ma kota
  [1,2] = Siała baba mak
  [1,3] = Matlab
}



* `cellstr()` zamiana tablicy znakowej na znakową macierz komórkową. Wypełniające blanki zostają usunięte.
* `char()`  zamiana macierzy komórkowej na znakową
* `iscellstr()` sprawdza, czy macierz jest macierzą komórkową z napisami 

In [101]:
x = char('raz', 'dwa', 'trzy', 'cztery')
y = cellstr(x)
whos x y
sprintf('Dlugosc napisu %s wynosi %d\n', x(1,:), length(x(1, :))
% fprintf('Dlugosc napisu %s wynosi %d\n', y(1), length(y{1}))
% length(y{1})



x =

raz   
dwa   
trzy  
cztery

y =
{
  [1,1] = raz
  [2,1] = dwa
  [3,1] = trzy
  [4,1] = cztery
}

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        x           4x6                         24  char
        y           4x1                         16  cell

Total is 28 elements using 40 bytes




Continuation prompt found - input was incomplete:
x = char('raz', 'dwa', 'trzy', 'cztery')
y = cellstr(x)
whos x y
sprintf('Dlugosc napisu %s wynosi %d\n', x(1,:), length(x(1, :))
% fprintf('Dlugosc napisu %s wynosi %d\n', y(1), length(y{1}))
% length(y{1})


In [105]:
tekst = {'raz', 'dwa', 'trzy', 'cztery'};
x = char(tekst)
size(x)
whos x

x =

raz   
dwa   
trzy  
cztery

ans =

   4   6



In [109]:
tekst = {'raz', 'dwa', 'trzy', 'cztery'};
s = char(tekst);

whos tekst s

a = iscellstr(tekst)
b = iscellstr(s)
c = iscellstr({1 , 'A', 'Ala'})


Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        tekst       1x4                         16  cell
        s           4x6                         24  char

Total is 28 elements using 40 bytes

a = 1
b = 0


**Ćwiczenie**: utwórz tablicę komórkową zawierająca listę imion (np. Ala, Ewa, Janek), drugą zawierająca listę czasowników (np. lubi, je, czyta) i trzecia zawierającą rzeczowniki (np. kamienie, kotlety, koty).  Napisz wyrażenie (lub funkcję), które tworzy zdania losując po jednym wyrazie z każdego zbioru (np. Ala lubi koty)

## Struktury

* funkcja `struct()` pozwala tworzyć struktury. Argumentami funkcji są kolejne pary określające nazwę pola i wartość
* struktyry posiadają nazwane **pola** przechowujące wartości dowolnego typu
* `struktura.pole` dostęp do pól struktury za pomocą kropki


In [138]:
s = struct('liczba', 42, 'nazwa', 'Matlab', 'tablica', 1:2:10, 'komórka', {1, 2, 3})
s
whos s   % ta struktura jest macierza 1x1

s =

  1x3 struct array containing the fields:

    liczba
    nazwa
    tablica
    komórka

s =

  1x3 struct array containing the fields:

    liczba
    nazwa
    tablica
    komórka



In [135]:
s.liczba


s.nazwa 
s.tablica 
s.komórka

ans =  42
ans =  42
ans =  42
ans = Matlab
ans = Matlab
ans = Matlab
ans =

   1   3   5   7   9

ans =

   1   3   5   7   9

ans =

   1   3   5   7   9



Inline plot failed, consider trying another graphics toolkit
parse error:

  syntax error

>>> s.komórka
         ^




* struktury można też tworzyć przypisując wartości polom struktury 

In [143]:
struktura.pole = 5;
whos struktura
disp(struktura)
disp(struktura.pole)


Variables in the current scope:

   Attr Name           Size                     Bytes  Class
   ==== ====           ====                     =====  ===== 
        struktura      1x1                          8  struct

Total is 1 element using 8 bytes

  scalar structure containing the fields:

    pole =  5


* `rmfield(s, n)` usuwa ze sruktury `s` pole o nazwie `n`
* `isstruct(s)` spradza, czy `s` jest strukturą
* `isfield(s, n)` sprawdza, czy pole o nazwie `n` znajduje się w strukturze `s`
* `fieldnames(s)` zwraca listę (cell array) nazw pól



In [152]:
s = struct('liczba', 42, 'nazwa', 'Matlab', 'macierz', rand(5));
disp(s)

nazwy = fieldnames(s)
disp(nazwy)

  scalar structure containing the fields:

    liczba =  42
    nazwa = Matlab
    macierz =

       0.786267   0.232297   0.468824   0.788395   0.450492
       0.412865   0.417000   0.693545   0.610671   0.646716
       0.357981   0.514515   0.065028   0.130114   0.837624
       0.206918   0.355553   0.246660   0.815622   0.084412
       0.034342   0.915617   0.024297   0.974501   0.888532

nazwy =
{
  [1,1] = liczba
  [2,1] = nazwa
  [3,1] = macierz
}



In [149]:
rmfield(s, 'macierz')
disp(s)

% podstawiamy wynik 
s = rmfields(s, 'macierz')
disp(s)

  scalar structure containing the fields:

    liczba =  42
    nazwa = Matlab
    macierz =

       0.744544   0.403936   0.317031   0.371388   0.961494
       0.032316   0.262667   0.057570   0.368793   0.902559
       0.427680   0.226120   0.804888   0.987200   0.443375
       0.723390   0.051866   0.459907   0.330884   0.468431
       0.040685   0.992671   0.263255   0.566949   0.813592

ans =

  scalar structure containing the fields:

    liczba =  42
    nazwa = Matlab

  scalar structure containing the fields:

    liczba =  42
    nazwa = Matlab
    macierz =

       0.744544   0.403936   0.317031   0.371388   0.961494
       0.032316   0.262667   0.057570   0.368793   0.902559
       0.427680   0.226120   0.804888   0.987200   0.443375
       0.723390   0.051866   0.459907   0.330884   0.468431
       0.040685   0.992671   0.263255   0.566949   0.813592

error: 'rmfields' undefined near line 1 column 5


In [ ]:
a = isfield(s, 'liczba')
b = isfield(s, 'xxx')

In [155]:

s.('liczba')


a = 1
b = 0
ans =  42


## Wektory i macierze struktur

* struktury moga byc elementami wektorów i macierzy (struct array)


In [160]:
sm(1).pole = 5
sm(2).pole = 42
whos sm



sm =

  scalar structure containing the fields:

    pole =  5

sm =

  1x2 struct array containing the fields:

    pole



In [161]:
# prealokacja macierzy strukrur przez zdefiniowanie ostatniego elementu

sa(10).pole = 3
whos sa
disp(sa)

sa =

  1x10 struct array containing the fields:

    pole

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        sa          1x10                         8  struct

Total is 10 elements using 8 bytes



In [165]:
sb(10,10).pole = 5
whos sb
disp(sb)
a = sb(1,1).pole
b = sb(:, 1).pole

sb =

  10x10 struct array containing the fields:

    pole

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        sb         10x10                         8  struct

Total is 100 elements using 8 bytes

  10x10 struct array containing the fields:

    pole
a = [](0x0)


In [172]:
% alokacja macierzy struktur za pomocą funkcji repmat
s3 = repmat(struct('pole', 42, 'nazwa', 'Matlab'), 2, 3)
whos s3
disp(s3)
size(s3)
a = s3(1, 2).pole
s3.pole
whos a

s3 =

  2x3 struct array containing the fields:

    pole
    nazwa

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        s3          2x3                         84  struct

Total is 6 elements using 84 bytes

  2x3 struct array containing the fields:

    pole
    nazwa
ans =

   2   3

a =  42
ans =  42
ans =  42
ans =  42
ans =  42
ans =  42
ans =  42


In [174]:
% umieszczenie wartości pól w wektorze
a = [ s3.pole ]
whos a
size(a)

a =

   42   42   42   42   42   42

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x6                         48  double

Total is 6 elements using 48 bytes



## Zagnieżdzone struktury

* polami struktur moga być dowolne zmienne, w tym inne struktury

In [178]:
st = struct('pole1', struct('a', 13, 'b', 14), 'pole2', struct('x', -1))
disp(st)

% pole 1 jest strukturą
a = st.pole1

% struktura w polu1 ma pole 'a'
b = st.pole1.a


st =

  scalar structure containing the fields:

    pole1 =

      scalar structure containing the fields:

        a =  13
        b =  14

    pole2 =

      scalar structure containing the fields:

        x = -1


  scalar structure containing the fields:

    pole1 =

      scalar structure containing the fields:

        a =  13
        b =  14

    pole2 =

      scalar structure containing the fields:

        x = -1

a =

  scalar structure containing the fields:

    a =  13
    b =  14



**Ćwiczenie** zaprojektuj i utwórz strukturę, która będzie przechowywała dane dotyczące studenta, takie jak: imię, nazwisko, data urodzenia (data zawiera osobne wartości: dzień, miesiąc, rok), miejsce zamieszkania (adres zawiera pola: ulica, numer domu, kod pocztowy, kraj). 

* `cell2struct()`
* `struct2cell()`